### ISSUE TITLE
removing_files tasks fail if Singularity isn't configured to automatically bind the top-level working directory

### ISSUE THREAD

**Issue by denriquez** [tgen/tempe#11]
**tempe version:** 1.1.0
**task:** removing_files (remove_files)
**Issue:** Task fails because a generated script (cmd) file located on user's working directory couldn't be found. The Singularity execution command didn't bind the user's working directory (-B bind option) for this task.
**Example of error message (paths and sample names were modified):**
`
/usr/bin/bash: $USER_SCRATCH/tempe/EXAMPLE_01/jetstream/cmd/1111111111111_removing_files_no_baserecalibration_EXAMPLE_01_L0001_GermlineDNA_parabricks.cmd: No such file or directory
`

**Comment by bryce-turner** [comment]
We can and probably should add an input to `removing_files`, it currently uses before-re and after-re. Adding `{{ directory }}` to input would ensure that it is mounted.

However, in this case, `$USER_SCRATCH/tempe/EXAMPLE_01/jetstream/cmd/1111111111111_removing_files_no_baserecalibration_EXAMPLE_01_L0001_GermlineDNA_parabricks.cmd` should always be available. I'll test and investigate this further.

**Comment by bryce-turner** [comment]
Added `{{ directory }}` as input in #13 - this should also be solved by https://github.com/tgen/jetstream/pull/152
