### ISSUE TITLE
Need to make this dynamic to support >40 BQ

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/tempe#31]
https://github.com/tgen/tempe/blob/57541f2249741b2c7e25d47cdf6dbafd0ac5d291/required_scripts/summarize_samstats_8c45d63.R#LL113C44-L113C74

**Comment by PedalheadPHX** [comment]
@bryce-turner I believe we did fix this

**Comment by bryce-turner** [comment]
Correct, I'll add this to the release notes and close this issue accordingly
