### ISSUE TITLE
Excessive CPU usage

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/tempe#40]
https://github.com/tgen/tempe/blob/7575cec83822ed77b0d0747e0ff3cf91dfd7a956/modules/dna_alignment/bwa_mem2_samtools.j2#L168

markdup is largely single threaded, using 20 only has an advantage for bam compression at the end, suggest 4 threads?

**Comment by PedalheadPHX** [comment]
This is only 4 in phoenix

**Comment by bryce-turner** [comment]
Fixed in https://github.com/tgen/tempe/releases/tag/v1.2.0
