### ISSUE TITLE
Output VEP cononical/pick/Mane

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/tempe#41]
https://github.com/tgen/tempe/blob/7575cec83822ed77b0d0747e0ff3cf91dfd7a956/modules/annotation/vep.j2#L106-L107

pick would be the old nomenclature, should maybe changed to "mane"

**Comment by PedalheadPHX** [comment]
guess it is still the pick process, just mane is not priority order

**Comment by bryce-turner** [comment]
Consistent with https://github.com/tgen/tempe/releases/tag/v1.2.0, pick order uses mane as top priority, overall pick order was updated for consistency with VEP/Ensembl pick order
