### ISSUE TITLE
Samtools merge CPU

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/tempe#43]
https://github.com/tgen/tempe/blob/7575cec83822ed77b0d0747e0ff3cf91dfd7a956/modules/dna_alignment/bwa_mem2_samtools.j2#L114

in phoenix we only use 8 not 16 with the same 8G ram

**Comment by bryce-turner** [comment]
Fixed in https://github.com/tgen/tempe/releases/tag/v1.2.0
