### ISSUE TITLE
Genome Deepvariant postprocess_variants Memory Issue

### ISSUE THREAD

**Issue by denriquez** [tgen/tempe#61]
**Tempe Version**:  1.2.1

**Task Name**:  deepvariant_postprocess_variants

**Issue**:  We are experiencing failures due to out of memory when running this task when using genome samples. We had no issues with any exome data. The recent test that failed used the 40G memory bin since it was just under 1 billion reads. The memory_bins would need to be increased and/or read_bins adjusted.

Brief info on the sample that failed: 
total reads=920,678,408
%duplicates=39
mean coverage=26

**Comment by bryce-turner** [comment]
Seems to be largely fixed by the recent #62 PR - bins were shifted by 16G at each level. Will be released in v1.2.2 - closing this issue as it is part of the development branch.
