### ISSUE TITLE
Vardict Chunk 4 Task Hitting Wall-Time for Genomes

### ISSUE THREAD

**Issue by denriquez** [tgen/tempe#65]
**Tempe Version**: 1.2.1

**Task Name**: vardict_[pair-name]_4

**Issue**: We are experiencing failures due to hitting the wall time specifically for genome samples. We had no issues with any exome data. I have tested 12 different projects and they all encountered this issue.

**Comment by bryce-turner** [comment]
Staged as part of #64 - currently debating on if additional regions should be modified since we will need to recompute anyway.

**Comment by PedalheadPHX** [comment]
Can we get a count comparison for samples ran on the 6000 vs X, I'm worried this is a two fold issue, bad genome region AND an event that is worse on the X than the 6000. There are a few genomes where the same library was done on both for TSCA, should be GM12878 replicates also but likely not the same library
